/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package di.uniba.it.tri.shell.gui;

import org.jfree.chart.ChartPanel;

/**
 *
 * @author pierpaolo
 */
public class ChartDialog extends javax.swing.JDialog {

    private final ChartPanel chartPanel;

    /**
     * Creates new form ChartDialog
     */
    public ChartDialog(java.awt.Frame parent, boolean modal, ChartPanel chartPanel) {
        super(parent, modal);
        this.chartPanel = chartPanel;
        initComponents();
        initMy();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initMy() {
        this.getContentPane().add(chartPanel, java.awt.BorderLayout.CENTER);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
